### ISSUE TITLE
4월 23일 패치 이후 vladmandic와 호환이 되지 않습니다.

### ISSUE THREAD

**Issue by wkdtjs** [NeoGraph-K/sd-webui-ddsd#7]
----------------------------------------------------------------------------------------------------------------------------
Running script postprocess image: D:\vladmandic\automatic\extensions\sd-webui-ddsd\scripts\ddsd.py: KeyError
╭───────────────────────────────────────── Traceback (most recent call last) ──────────────────────────────────────────╮
│ D:\vladmandic\automatic\modules\scripts.py:462 in postprocess_image                                                  │
│                                                                                                                      │
│   461 │   │   │   │   script_args = p.script_args[script.args_from:script.args_to]                                   │
│ ❱ 462 │   │   │   │   script.postprocess_image(p, pp, *script_args)                                                  │
│   463 │   │   │   except Exception as e:                                                                             │
│                                                                                                                      │
│ D:\vladmandic\automatic\extensions\sd-webui-ddsd\scripts\ddsd.py:608 in postprocess_image                            │
│                                                                                                                      │
│   607 │   │   if not self.disable_detailer:                                                                          │
│ ❱ 608 │   │   │   output_image = self.dino_detect_detailer(p, output_image,                                          │
│   609 │   │   │   │   │   │   │   │   │   │   │   │   │    self.disable_mask_paint_mode, self.                       │
│                                                                                                                      │
│ D:\vladmandic\automatic\extensions\sd-webui-ddsd\scripts\ddsd.py:332 in dino_detect_detailer                         │
│                                                                                                                      │
│   331 │   │   │   self.change_ckpt_model(dino_detection_ckpt_list[detect_index] if dino_detect                       │
│ ❱ 332 │   │   │   self.change_vae_model(dino_detection_vae_list[detect_index] if dino_detectio                       │
│   333 │   │   │   if len(dino_detection_prompt_list[detect_index]) < 1: continue                                     │
│                                                                                                                      │
│ D:\vladmandic\automatic\extensions\sd-webui-ddsd\scripts\ddsd.py:494 in change_vae_model                             │
│                                                                                                                      │
│   493 │   │   elif name == 'none': modules.sd_vae.reload_vae_weights(shared.sd_model, vae_file                       │
│ ❱ 494 │   │   else: modules.sd_vae.reload_vae_weights(shared.sd_model, vae_file=modules.sd_vae                       │
│   495                                                                                                                │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
KeyError: 'Automatic'
Running script postprocess: D:\vladmandic\automatic\extensions\sd-webui-ddsd\scripts\ddsd.py: KeyError
╭───────────────────────────────────────── Traceback (most recent call last) ──────────────────────────────────────────╮
│ D:\vladmandic\automatic\modules\scripts.py:446 in postprocess                                                        │
│                                                                                                                      │
│   445 │   │   │   │   script_args = p.script_args[script.args_from:script.args_to]                                   │
│ ❱ 446 │   │   │   │   script.postprocess(p, processed, *script_args)                                                 │
│   447 │   │   │   except Exception as e:                                                                             │
│                                                                                                                      │
│ D:\vladmandic\automatic\extensions\sd-webui-ddsd\scripts\ddsd.py:505 in postprocess                                  │
│                                                                                                                      │
│   504 │   │   self.change_ckpt_model(self.ckptname)                                                                  │
│ ❱ 505 │   │   self.change_vae_model(self.vae)                                                                        │
│   506                                                                                                                │
│                                                                                                                      │
│ D:\vladmandic\automatic\extensions\sd-webui-ddsd\scripts\ddsd.py:494 in change_vae_model                             │
│                                                                                                                      │
│   493 │   │   elif name == 'none': modules.sd_vae.reload_vae_weights(shared.sd_model, vae_file                       │
│ ❱ 494 │   │   else: modules.sd_vae.reload_vae_weights(shared.sd_model, vae_file=modules.sd_vae                       │
│   495                                                                                                                │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
KeyError: 'Automatic'
----------------------------------------------------------------------------------------------------------------------------

**Comment by NeoGraph-K** [comment]
해당 이슈는 Automatic 문자열의 대소문자를 구분하지 못한 오류이며 현재 해결되었습니다.
