### ISSUE TITLE
Is it possible to show mask on the live preview window during processing?

### ISSUE THREAD

**Issue by blueball81** [NeoGraph-K/sd-webui-ddsd#8]
Hi, 

This extension looks fantastic to fix images automatically.
But, as you know, sometimes the detection/segmentation does not work properly, and gives unintended results.

Do you think this extension is able to show acquired masks/segmentation results on the live preview window during processing?
In this way, we don't need to go the image browser after image generation to check whether the mask was acquired properly or not. The result mask on the preview window doesn't need to be saved as a file, but to show only on the screen.

The original Detection Detailer by dustysys (https://github.com/dustysys/ddetailer) shows the acquired mask on the live preview as in the following screen captures. 

Please, consider to implement this funtionality. Thanks,

Examples: https://github.com/dustysys/ddetailer/issues/4#issuecomment-1311200268
![image](https://user-images.githubusercontent.com/1153785/234031531-f79723b8-6faf-449c-8f82-17a20f2eba29.png)

**Comment by NeoGraph-K** [comment]
Several people have requested this feature and are checking it out. To create that feature, you need to check the preview process, so it will take some time.

**Comment by blueball81** [comment]
Thanks for considering this feature. 

Just FYI, here I leave some codes that I found. I hope this would help for your work. 

Looking at the codes of DDetailer, it seems that it is just handover the mask image to the variable, shared.state.current_image, as in the following. 

ddetailer.py
<img width="1054" alt="image" src="https://user-images.githubusercontent.com/1153785/234500798-e579e2f5-5451-4e7c-8b35-0b2a71e8c337.png">

Also, it is also possible to show/add mask images in the preview window after the processing as in the following code, using ‘processed.images.extend’ method.

controlnet.py
<img width="1014" alt="image" src="https://user-images.githubusercontent.com/1153785/234503303-92cc9cb6-e2cc-405b-8353-b3aaeb76ae62.png">

**Comment by NeoGraph-K** [comment]
Thanks for pointing out that code. I checked that code and it doesn't seem difficult to create behavior with that function. Let's add that feature as an option.

**Comment by NeoGraph-K** [comment]
I think I've fixed that issue.
However, when I turn on the preview option in my current environment, an error that does not work occurs, making it impossible to check. Please test and give feedback on this issue if you have any problems.
