### ISSUE TITLE
안녕하세요 히히호호입니다.

### ISSUE THREAD

**Issue by todhm** [NeoGraph-K/sd-webui-ddsd#9]
선생님 안녕하세요? 고생이 많으십니다. 
저 히히호호 feed extension 개발자인디요.

선생님 작업이 궁금해서 혹시 이야기좀 나눌수 있을까해서? 
혹시 뭐 디코나, 오픈카톡방 혹은 뭐 제 정보 남겨드리면 연락 가능합니까?

**Comment by NeoGraph-K** [comment]
오픈 카톡방 남겨주시면 연락 가능합니다.
디코는 개인적으로는 잘 안쓰고 오픈카톡방 열어주세요.

**Comment by todhm** [comment]
https://open.kakao.com/o/slLi3ehf 여기용!
